
services:
  flask-app:
    build: .
    ports:
      - "8777:5000"
    volumes:
      - ./Scores.txt:/Scores.txt
    command: ["python3", "/app/MainScores.py"]
    depends_on:
      - selenium
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  test:
    build:
      context: .
    entrypoint: []
    command: ["sh", "-c", "until curl -s http://flask-app:5000; do echo 'Waiting for Flask app to be ready...'; sleep 5; done && python3 e2e.py"]
    working_dir: /app
    depends_on:
      - flask-app
      - selenium
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
