
services:
  flask-app:
    build: .
    ports:
      - "8777:5000"
    volumes:
      - ./Scores.txt:/Scores.txt
      - .:/app
      - ./requirements.txt:/app/requirements.txt
    command: ["python3", "/app/MainScores.py"]
    depends_on:
      - selenium
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  test:
    build:
      context: .
    command: ["sh", "-c", "sleep 5 && python3 e2e.py"]
    depends_on:
      - flask-app
      - selenium
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
